import {
  motion,
  PageTransition,
  fadeInUp,
  staggerContainer,
} from "../utils/motion";
import { useNavigate } from "react-router-dom";
import "./Pages.css";

const STEPS = [
  {
    number: "01",
    title: "Select Your Profile",
    action:
      "Toggle Demo Mode in the top right, then pick a student from the dropdown.",
    why: "This loads a pre-built curriculum with 50 topics across 8 semesters. In a real deployment, you would log in with your university account instead.",
    where: "Dashboard, top-right corner",
  },
  {
    number: "02",
    title: "Take the Gap Finder Quiz",
    action:
      "Click Find My Gaps in the sidebar. Choose a subject. Answer the questions.",
    why: "The quiz maps each question to a specific topic in the curriculum. After you submit, the system scores you per topic, identifies where you scored below 60%, and classifies why you got it wrong (wrong concept, missing prerequisite, or calculation mistake). The fix is different for each type.",
    where: "Sidebar: Find My Gaps",
  },
  {
    number: "03",
    title: "See Your Results",
    action:
      "After submitting, scroll to see your scores and the root cause chain.",
    why: "This is the core feature. The system traces backward through prerequisites to find where your chain of understanding breaks. If you scored low on Support Vector Machines (Semester 6), it may trace back through Lagrange Multipliers (Sem 3) all the way to Matrix Operations (Sem 1). That Sem 1 topic is what you actually need to study first.",
    where: "Quiz results, below the score bars",
  },
  {
    number: "04",
    title: "Explore Your Learning Map",
    action:
      "Click See My Learning Map on the dashboard, or Learning Map in the sidebar.",
    why: 'The graph shows how all 50 topics connect across semesters. Arrows mean "requires." When you fail a topic, the system highlights the chain of prerequisites in red, all the way back to the root cause. This lets you see exactly where in your past semesters the gap started.',
    where: "Sidebar: Learning Map",
    how: [
      "Red circles = topics you scored below 60%",
      "Large red with glow = root cause (where the chain breaks)",
      "Green = topics you have mastered",
      "Orange = topics that are fading from memory",
      "Gray = topics not yet tested",
      "Arrows show what requires what (A -> B means A needs B)",
      "Hover any circle for details. Click it to see prerequisites.",
      "Use the search bar to find a specific topic by name.",
    ],
  },
  {
    number: "05",
    title: "Get Your Study Plan",
    action: "Go to Study Plan in the sidebar. Click Generate Remediation Plan.",
    why: "The system orders your gaps by prerequisite depth. You study foundational topics first, then build up. Each lesson is generated by AI, targeted to the specific type of mistake you made, not generic textbook content.",
    where: "Sidebar: Study Plan",
  },
  {
    number: "06",
    title: "Prioritize Before Exams",
    action:
      "Go to Exam Priority. Enter your exam date and how many hours you can study per day.",
    why: "When time is limited, the system calculates which topics unlock the most dependent concepts. A topic that five other topics depend on gets higher priority than one with no dependents. You study what gives the highest return first.",
    where: "Sidebar: Exam Priority",
  },
];

export default function HowToPage() {
  const navigate = useNavigate();

  return (
    <PageTransition>
      <div style={{ maxWidth: 760 }}>
        <h1 className="page-title">How to Use SkillGraph</h1>
        <p className="page-subtitle" style={{ marginBottom: 8 }}>
          Follow these 6 steps. Each one builds on the previous.
        </p>
        <p
          style={{
            fontSize: "0.82rem",
            color: "var(--text-tertiary)",
            marginBottom: 28,
            lineHeight: 1.6,
          }}
        >
          SkillGraph finds the hidden reason you fail courses. It is not that
          you did not study. It is that you are missing a prerequisite from
          semesters ago that nobody told you about.
        </p>

        <motion.div
          variants={staggerContainer}
          initial="initial"
          animate="animate"
          style={{ display: "flex", flexDirection: "column", gap: 16 }}
        >
          {STEPS.map((step) => (
            <motion.div
              key={step.number}
              className="card"
              variants={fadeInUp}
              style={{ padding: "20px 24px" }}
            >
              <div
                style={{ display: "flex", gap: 16, alignItems: "flex-start" }}
              >
                <div
                  style={{
                    fontSize: "1.6rem",
                    fontWeight: 700,
                    color: "var(--accent)",
                    lineHeight: 1,
                    minWidth: 36,
                  }}
                >
                  {step.number}
                </div>
                <div style={{ flex: 1 }}>
                  <div
                    style={{
                      fontWeight: 600,
                      fontSize: "1rem",
                      marginBottom: 6,
                    }}
                  >
                    {step.title}
                  </div>

                  <div
                    style={{
                      background: "rgba(124,92,252,0.08)",
                      borderRadius: 6,
                      padding: "10px 14px",
                      marginBottom: 10,
                      fontSize: "0.88rem",
                      color: "var(--text-primary)",
                      fontWeight: 500,
                    }}
                  >
                    {step.action}
                  </div>

                  <p
                    style={{
                      fontSize: "0.84rem",
                      color: "var(--text-secondary)",
                      lineHeight: 1.6,
                      margin: 0,
                    }}
                  >
                    {step.why}
                  </p>

                  {step.how && (
                    <div style={{ marginTop: 12 }}>
                      <div
                        style={{
                          fontSize: "0.78rem",
                          fontWeight: 600,
                          color: "var(--text-primary)",
                          marginBottom: 6,
                        }}
                      >
                        What the colors mean:
                      </div>
                      <div
                        style={{
                          display: "flex",
                          flexDirection: "column",
                          gap: 3,
                        }}
                      >
                        {step.how.map((item, i) => (
                          <span
                            key={i}
                            style={{
                              fontSize: "0.78rem",
                              color: "var(--text-secondary)",
                            }}
                          >
                            {item}
                          </span>
                        ))}
                      </div>
                    </div>
                  )}

                  <div
                    style={{
                      marginTop: 8,
                      fontSize: "0.72rem",
                      color: "var(--text-tertiary)",
                    }}
                  >
                    Where: {step.where}
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </motion.div>

        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.5 }}
          style={{ marginTop: 28, textAlign: "center" }}
        >
          <motion.button
            className="btn btn-primary"
            whileHover={{ scale: 1.03 }}
            whileTap={{ scale: 0.97 }}
            onClick={() => navigate("/")}
            style={{ marginRight: 12 }}
          >
            Go to Dashboard
          </motion.button>
          <motion.button
            className="btn btn-secondary"
            whileHover={{ scale: 1.03 }}
            whileTap={{ scale: 0.97 }}
            onClick={() => navigate("/quiz")}
          >
            Start Finding Gaps
          </motion.button>
        </motion.div>
      </div>
    </PageTransition>
  );
}
